### ISSUE TITLE
How can I use parameteres?

### ISSUE THREAD

**Issue by Marmoulak** [AlexxIT/PythonScriptsPro#31]
Hi
I exec a paython file from Call service node from Node-red and added this code:
```json
{
    "file": "/config/python_scripts/unifi/unifi_led.py",
    "state": "on"
}
```

it call and execute unifi_led.py but without parameters and when I exec the file from cmd prompt with parameters it works without problem. 
I have tried to call the service with fowling code but did not help:
```yaml
service: python_script.exec
data:
  file: {
    "file": "/config/python_scripts/unifi/unifi_led.py",
    "state": "on"

}
```
what do I do wrong? 

cmd:
python unifi_led.py -state on

![image](https://github.com/user-attachments/assets/758aec3d-72e6-41d0-8edb-cec67833e992)

**Comment by AlexxIT** [comment]
If your script takes variables from `sys.argv` - this is not supported.
There is an example of how to use variables in the documentation:
https://github.com/AlexxIT/PythonScriptsPro?tab=readme-ov-file#run-script-from-python-file

**Comment by fastbobjorn** [comment]
Hi,

Thanks for putting so much effort in your scripts. Great work !
I have a question about using input parameters regarding PythonScriptPro:

Is it possible to pass parameters when using a sensor and file, like the example below:

```
sensor:
  - platform: python_script
    name: Test
    scan_interval: '00:00:10'  
    file: /config/my_python_scripts/test.py
```
